name: 'Frontend Super Deluxe'
on:
  workflow_call:
    inputs:
      npm-publish:
        description: Publish to registry
        required: true
        type: boolean
        default: false
jobs:
  npm:
    uses: jonasthim/reusable-workflows/.github/workflows/npm.yml@main
    secrets: inherit
    with: 
      npm-publish: ${{ inputs.npm-publish }}
  licenses:
    uses: jonasthim/reusable-workflows/.github/workflows/licenses.yml@main
    needs: npm
    secrets: inherit
  spectral:
    uses: jonasthim/reusable-workflows/.github/workflows/spectral.yml@main
    needs: npm
    secrets: inherit
  trivy:
    uses: jonasthim/reusable-workflows/.github/workflows/trivy.yml@main
    needs: npm
    secrets: inherit
  checkov:
    uses: jonasthim/reusable-workflows/.github/workflows/checkov.yml@main
    needs: npm
    secrets: inherit
  # deploy:
  #   uses: jonasthim/reusable-workflows/.github/workflows/checkov.yml@main
  #   secrets: inherit
