name: 'Cloudflare'
on:
  workflow_call:
jobs:
  npm:
    uses: jonasthim/reusable-workflows/.github/workflows/npm.yml@main
    secrets: inherit
  licenses:
    uses: jonasthim/reusable-workflows/.github/workflows/licenses.yml@main
    secrets: inherit
