name: 'Licenses'
on:
  workflow_call:
jobs:
  licenses:
    runs-on: ubuntu-latest
    name: License compliance
    steps:
      - name: Get files from cache
        uses: actions/download-artifact@v3
        with:
          name: Unpack build
          path: ./
      - name: License compliance check
        uses: mikaelvesavuori/license-compliance-action@v1.0.2